"""
config.py
Daniel Goldbach
2013 November

Constants, filenames, directories, etc.
"""


CACHE_DIR = '../cache/'

# Location of data sets generated by gen.py
TRAINING_SET_DIR = '../no_probe_set/'

RAW_TRAINING_MED_DIR = '../training_med/'
RAW_TRAINING_LRG_DIR = '../training_set/'
RAW_PROBE_FN = '../probe.txt'

# Generated by gen.py
RATED_PROBE_FN = '../probe_rated.txt'

GENERATED_DIRS = (CACHE_DIR, TRAINING_SET_DIR)

# LSH parameters
BLOCK_SIZE = 16   # k
NUM_BLOCKS = 500  # l
